---
- hosts: winserver19
  gather_facts: true
  tasks:
    - name: 6.8.1 Proteger enrutamiento de origen IP
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: DisableIPSourceRouting
        type: dword
        data: 2
      notify:
        - Reiniciar servidor

    - name: 6.8.2 Puertas de enlace inactivas
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: EnableDeadGWDetect
        type: dword
        data: 0
      notify:
        - Reiniciar servidor

    - name: 6.8.3 Carga de transmisiones incompletas en conexiones SYN
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: SynAttackProtect
        type: dword
        data: 2
      notify:
        - Reiniciar servidor
    
    - name:  6.8.4 par치metro DisabledComponents de TCPIP6 est치 ajustado a 0xff(255) Win2022
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
        name: DisabledComponents
        type: dword
        data: 255
      when:
        - ansible_distribution.find("Microsoft Windows Server 2022") != -1
      notify:
        - Reiniciar servidor
    
    - name:  6.8.5 Remote Desktop Services configurado con el cifrado de la conexi칩n del cliente establecido en Nivel alto
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
        name: MinEncryptionLevel
        type: dword
        data: 3
      when: >
        ansible_distribution.find("Microsoft Windows Server 2022") != -1
        or
        ansible_distribution.find("Microsoft Windows Server 2019") != -1
      notify:
        - Reiniciar servidor
    
    - name: 6.8.6 Indexaci칩n de archivos encriptados
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search
        name: AllowIndexingEncryptedStoresOrItems
        type: dword
        data: 0
      when: >
        ansible_distribution.find("Microsoft Windows Server 2022") != -1
        or
        ansible_distribution.find("Microsoft Windows Server 2019") != -1
      notify:
        - Reiniciar servidor

    - name: "6.8.7 Domain member: Digitally encrypt or sign secure channel data se encuentra activado"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
        name: RequireSignOrSeal
        type: dword
        data: 1
      when: >
        ansible_distribution.find("Microsoft Windows Server 2022") != -1
        or
        ansible_distribution.find("Microsoft Windows Server 2019") != -1
      notify:
        - Reiniciar servidor

    - name: "6.8.8 Domain member: Digitally encrypt secure channel data se encuentra activado"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
        name: SealSecureChannel
        type: dword
        data: 1
      when: >
        ansible_distribution.find("Microsoft Windows Server 2022") != -1
        or
        ansible_distribution.find("Microsoft Windows Server 2019") != -1
      notify:
        - Reiniciar servidor

    - name: "6.8.9 Microsoft network client: Send unencrypted password to third-party SMB servers se encuentra deshabilitado"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
        name: EnablePlainTextPassword
        type: dword
        data: 0
      when: >
        ansible_distribution.find("Microsoft Windows Server 2022") != -1
        or
        ansible_distribution.find("Microsoft Windows Server 2019") != -1
      notify:
        - Reiniciar servidor
    
    - name: "6.8.10  Allow Cloud Search se encuentra deshabilitado"
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search
        name: AllowCloudSearch
        type: dword
        data: 0
      when: >
        ansible_distribution.find("Microsoft Windows Server 2022") != -1
        or
        ansible_distribution.find("Microsoft Windows Server 2019") != -1
      notify:
        - Reiniciar servidor

    - name: "6.8.11 Allow indexing of encrypted files se encuentra deshabilitado"
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search
        name: AllowIndexingEncryptedStoresOrItems
        type: dword
        data: 0
      when: >
        ansible_distribution.find("Microsoft Windows Server 2022") != -1
        or
        ansible_distribution.find("Microsoft Windows Server 2019") != -1
      notify:
        - Reiniciar servidor

  handlers:
    - name: Reiniciar servidor
      win_reboot:
        reboot_timeout: 120

